### ISSUE TITLE
Where is ray tracing?

### ISSUE THREAD

**Issue by stefanpgd** [DylanoSol/visboer#1]
I think your engine could profit from a good ray tracing backend.

**Comment by DylanoSol** [comment]
For the current scope of this project, I am not looking for realistic graphics. The goal is to simply be able to visualise my physics world in a basic way, which simple rasterization using SDL2 can provide for me.

**Comment by stefanpgd** [comment]
:(

**Comment by stefanpgd** [comment]
I see how it is
